### ISSUE TITLE
Datastore 404.

### ISSUE THREAD

**Issue by StuxxyOfficial** [nightowlsrp/LindenESX-recipe#1]
[19:37:15] Running [task21:download_github]... ❌
[19:37:15] [task21:download_github] failed!
Message: Request failed with status code 404
Options:
{
"action": "download_github",
"src": "https://github.com/thelindat/esx_datastore",
"ref": "5f5105d419d21aa6fcdc2b6aa2156d9c40e58d82",
"dest": "./resources/[esx]/esx_datastore"
}

looks liked this resource doesn't exist anymore or am i missing something? I dont know what changes have been made from the vanilla version.

**Comment by nightowlsrp** [comment]
Fixed with latest update. Apparently Linden pulled his fork.
